"""Initial migration

Revision ID: 48043aaf735b
Revises: 
Create Date: 2025-12-12 22:29:06.583507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48043aaf735b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status_report',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('facility_id', sa.String(), nullable=False),
    sa.Column('status_type', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_notam_text', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_index(op.f('ix_status_report_facility_id'), 'status_report', ['facility_id'], unique=False)
    op.create_index(op.f('ix_status_report_report_id'), 'status_report', ['report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_status_report_report_id'), table_name='status_report')
    op.drop_index(op.f('ix_status_report_facility_id'), table_name='status_report')
    op.drop_table('status_report')
    # ### end Alembic commands ###
