FROM python:3.11-slim

WORKDIR /app
ENV PYTHONUNBUFFERED=1

# Install uv
RUN pip install uv

# Copy requirements for worker
COPY worker/requirements.txt .

# Install dependencies using uv
RUN uv pip install --system -r requirements.txt

# Copy source code
COPY common ./common
COPY worker ./worker

# Entrypoint command
CMD ["python", "worker/worker_job.py"]
